### ISSUE TITLE
Error and missing Labels

### ISSUE THREAD

**Issue by karlmira** [danielsaidi/PrintingKit#3]
I'm using printingKit for printing pdf files. Since Update of Sonoma to 14.4 in the printing dialogue some labels are not displayed properly and xcode prints out some messages

/.../SourcePackages/checkouts/PrintingKit/Sources/PrintingKit/Printer.swift:143 Failed to connect (genericPrinterImage) outlet from (PMPrinterSelectionController) to (NSImageView): missing setter or instance variable
/.../SourcePackages/checkouts/PrintingKit/Sources/PrintingKit/Printer.swift:143 Failed to connect (localPrintersLabel) outlet from (PMPrinterSelectionController) to (NSTextField): missing setter or instance variable
/.../SourcePackages/checkouts/PrintingKit/Sources/PrintingKit/Printer.swift:143 Failed to connect (otherPrintersLabel) outlet from (PMPrinterSelectionController) to (NSTextField): missing setter or instance variable
/.../SourcePackages/checkouts/PrintingKit/Sources/PrintingKit/Printer.swift:143 Failed to connect (recentPrintersLabel) outlet from (PMPrinterSelectionController) to (NSTextField): missing setter or instance variable

![Bildschirmfoto 2024-03-10 um 09 58 03](https://github.com/danielsaidi/PrintingKit/assets/111527454/a8604673-35b0-40a2-92e7-51eb3824a343)

I don't know if this is a bug in the system (macOS) or if new settings are needed.

**Comment by danielsaidi** [comment]
Hi @karlmira 

Interesting - it used before, right?

**Comment by karlmira** [comment]
Hi @danielsaidi 

very quick answer :-)

Yes, it worked great so far. Yesterday I made an update of Sonoma and today I recognized this behavior.

**Comment by danielsaidi** [comment]
That's interesting...I'll take a look when I use this package the next time. Until then, I'd love to hear of any more information that you may find or run into.

**Comment by danielsaidi** [comment]
Thank you for the sponsorship! 🙌 🍻

**Comment by karlmira** [comment]
You're very welcome. You are doing a great job.
It's not much, but it comes from my heart.

**Comment by danielsaidi** [comment]
It's truly appreciated! ❤️

**Comment by karlmira** [comment]
Hi @danielsaidi,

ok, looks like it's an issue of testing environment. In production environment this problem doesn't appear.

**Comment by danielsaidi** [comment]
Huh, that's strange! Is the test environment also on Sonoma?

**Comment by karlmira** [comment]
it's both the same ( Sonoma)

**Comment by danielsaidi** [comment]
😵

**Comment by danielsaidi** [comment]
Well, closing this for now then.

**Comment by jhoughjr** [comment]
I'm on Sequoia and the only thing I can print is .string it seems.
