### ISSUE TITLE
Crash - Print Image on Mac OS

### ISSUE THREAD

**Issue by asifbilal786** [danielsaidi/PrintingKit#8]
Hi, I am facing a crash issue in Mac OS when an application tries to print an image using this library as given in the below image

<img width="1398" alt="Screenshot 2024-07-04 at 10 49 07 PM" src="https://github.com/danielsaidi/PrintingKit/assets/937309/85142729-14c6-4bec-83a0-6ee9877d10ce">

Could you please look into this issue?

**Comment by danielsaidi** [comment]
Hi @asifbilal786 

Thank you for reporting this! Does it happen with all images?

I'll take a look when I get some time, and will also happily merge any PR that fixes it.

**Comment by asifbilal786** [comment]
Yes, it's happening to all images. It works best for iOS but crashes for the MacOS platform.

By the way, I was enjoying using this library until this happened. I appreciate it.

**Comment by danielsaidi** [comment]
Thank you for letting me know, I will check it out.

In the meantime, can you add more information about your runtime here, such as macOS version, Xcode/Swift version, etc.?

**Comment by asifbilal786** [comment]
Yes sure. Below are the details:

_Xcode Version_: **15.4**
_Swift Version_: **5.10**
_Mac OS_: **Sonoma 14.5**

**Comment by danielsaidi** [comment]
Thank you! 👍

**Comment by asifbilal786** [comment]
@danielsaidi Have you had any success resolving this issue?

**Comment by danielsaidi** [comment]
Hi @asifbilal786 

I haven't yet, but I'll let you know once I have and will be happy to merge any PR that solves it meanwhile.

**Comment by asifbilal786** [comment]
@danielsaidi with updating through SPM, this issue seems to be resolved. Therefore I am closing this issue

**Comment by danielsaidi** [comment]
Perfect, thank you for letting me know!
